name: Daily Purchase

on:
  workflow_dispatch:
  schedule:
    # This cron job runs every day at 12:00 UTC
    - cron: "0 12 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Install dependencies
        run: yarn

      - name: Run script
        run: yarn start
        env:
          KRAKEN_KEY: ${{ secrets.KRAKEN_KEY }}
          KRAKEN_SECRET: ${{ secrets.KRAKEN_SECRET }}
          DAILY_PURCHASE_AMOUNT_EUR: ${{ vars.DAILY_PURCHASE_AMOUNT_EUR }}
